#version: "3.9"
services:
  urlaubsplanung:
    image: hiiico/vacation_planning-urlaubsplanung
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:3306/vacation_planning?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BROKER}
    restart: unless-stopped