#version: "3.9"
services:
  urlaubsplanung:
    build:
      context: .
      dockerfile: Dockerfile
    image: hiiico/vacation_planning-urlaubsplanung
    container_name: main-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${MYSQL_HOST}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BROKER}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    expose:
      - "8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 50s
      retries: 10
#    depends_on:
#      mysql-db:
#        condition: service_healthy
#      kafka:
#        condition: service_healthy
    restart: unless-stopped

networks:
  app-network:
    external: true
    name: app-network